import datetime
t=datetime.datetime.now()
print(t)
print(t.date())
print(t.month)
print(t.year)
print(t.day)
print(t.time)
print(t.max)
print(t.min)
print(t.resolution)
print(t.today())
t.timetuple()
print(t.strftime("%A"))
x1=datetime.datetime(2020,7,5)
print(x1)
print(x1.day)
print(x1.strftime("%A"))
